/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zoho.mobile.inventory.system;

import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanele
 */
public class frmProductManagement extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmProductManagement
     */
    public frmProductManagement() {
        initComponents();
    }
    
    //A variable of type file that will be used to create a new file
    //to write to.
    File flProduct;
    
    //A  variable of type string that will hold user entered details.
    String[] arrFileContents;
    
    //A method that checks if the provided quantity is correct then
    //returns a value of type bolooen depending on the evaluation
    private boolean mCheckQuantityCorrectness()
    {
        boolean isCorrect = false;
        try{
            isCorrect = Integer.valueOf(txtQuantity.getText()) > 0 
                    && Integer.valueOf(txtQuantity.getText()) < Integer.MAX_VALUE;
        }catch(NumberFormatException eX){
            JOptionPane.showMessageDialog(null, txtQuantity.getText()+" is not an integer number");
            txtQuantity.requestFocusInWindow();
        }
        return isCorrect;
    }
    
    //A method that gets GUI entered values, concatenate and assign them to
    //variable arrFileContents.
    private void mGetValuesFromGUI()
    {
        arrFileContents = new String[]{
            txtProductName.getText(), txtQuantity.getText(),
            txtDescription.getText()
        };
    }
    
    //A method that clears GUI text fields.
    private void mClear()
    {
        txtProductName.setText("");
        txtQuantity.setText("");
        txtDescription.setText("");
    }
    
    //A method that checks if an accountant file already exits and
    //delete it if it does then create a new file. Whether a file 
    //exists or not, a new file is created either way.
    private void mCheckIfProductFileExists()
    {
        flProduct = new File(txtProductName.getText().toUpperCase()+".txt");
        if(flProduct.exists())
        {
            flProduct.delete();
        }
        mCreateProductFile();
    }
    
    //A method that creates a new file using the File variable flProduct.
    private void mCreateProductFile()
    {
        try
        {
            flProduct.createNewFile();
        }
        catch(IOException eX)
        {
            JOptionPane.showMessageDialog(null, "Something went wrong while creating file.\n"+eX.getMessage());
        }
    }
    
    //A method that writes to the newly created file
    private void mWriteProductDetailsToFile()
    {
        String strProduct = txtProductName.getText().toUpperCase()+".txt";
        try
        {
            try (java.io.FileWriter fw = new java.io.FileWriter(strProduct, true)) {
                for (String productDetails : arrFileContents) {
                    fw.write(productDetails+" ");
                }
                fw.close();
            }
            JOptionPane.showMessageDialog(null, "File added successfully.");
        }
        catch(IOException eX)
        {
            JOptionPane.showMessageDialog(null, "Something went wrong while writing file.\n"+eX.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        jspProductDescription = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 255, 204));

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeading.setText("Add Product");

        lblProductName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProductName.setText("Product");

        lblQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQuantity.setText("Quantity");

        lblDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDescription.setText("Description");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jspProductDescription.setViewportView(txtDescription);

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProductName)
                                    .addComponent(lblQuantity)
                                    .addComponent(lblDescription))
                                .addGap(164, 164, 164)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(jspProductDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(txtProductName, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(74, 74, 74)
                                .addComponent(btnClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                .addComponent(btnClose))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(lblHeading)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeading)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductName)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescription)
                    .addComponent(jspProductDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnClear)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(txtProductName.getText().equals("")){//Checks if txtProductName has been passed a value
            JOptionPane.showMessageDialog(null, "Please enter product name.");
            txtProductName.requestFocusInWindow();//Places the cursor inside txtProductName
        }else if(txtQuantity.getText().equals("")){//Checks if txtQuantity has been passed a value
            JOptionPane.showMessageDialog(null, "Please enter product quantity.");
            txtQuantity.requestFocusInWindow();//Places the cursor inside txtQuantity
        }else if(txtDescription.getText().equals("")){//Checks if txtDescription has been passed a value
            JOptionPane.showMessageDialog(null, "Please enter product description.");
            txtDescription.requestFocusInWindow();//Places the cursor inside txtDescription
        }else if(mCheckQuantityCorrectness()){//Checks for the correctness of given qantity value
            mGetValuesFromGUI();
            mCheckIfProductFileExists();
            mWriteProductDetailsToFile();
            mClear();
        }else{//if given quantity is not correct the follow message box pops up
            JOptionPane.showMessageDialog(null, "Product quantity must be any integer number between 1 and "+Integer.MAX_VALUE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        mClear();//This button event invokes a method that clears text fields
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        //This button event invokes a method that destroys an active 
        //object using the following line
        this.hide();
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jspProductDescription;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
